app/models.py
from app import db


class Libro(db.Model):
    __tablename__ = 'libros'

    #Crear las columnas de la tabla libros
    id = db.Column(db.Integer, primary_key = True)
    titulo = db.Column(db.String(100), nullable =  False)
    autor = db.Column(db.String(100), nullable = False)
    editorial = db.Column(db.String(100), nullable = False)

app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from config import Config

db = SQLAlchemy()
migrate = Migrate()

def create_app():
    app = Flask(__name__)

    # Configuración de la app
    app.config.from_object(Config)

    # Inicialización de las extensiones
    db.init_app(app)
    migrate.init_app(app, db)

    from app import models
    from app.routes.libros import libros_bp
    from app.routes.home import home_bp

    # Registrar Blueprints
    app.register_blueprint(libros_bp)
    app.register_blueprint(home_bp)

    return app

app/routes/home.py
from flask import Blueprint, jsonify

home_bp = Blueprint("home", __name__)

@home_bp.route("/")
def home():
    return jsonify({"status": "sucess", "menssage": "Mi primer proyecto en Flask"})

app/routes/libros.py
from flask import Blueprint, request, render_template, redirect, url_for
from flask import flash, get_flashed_messages, redirect, url_for
#from app.models import Usuario, Libro
from app.models import Libro
from datetime import datetime
from app import db
from flask import jsonify


libros_bp = Blueprint("libros", __name__)

@libros_bp.route("/libros", methods=["GET", "POST"])
def users():
    if request.method == "POST":
        titulo = request.form.get("titulo")
        autor = request.form.get("autor")
        editorial = request.form.get("editorial")

        nuevo_libro = Libro(titulo=titulo, autor=autor, editorial=editorial)

        db.session.add(nuevo_libro)
        db.session.commit()

        flash("Libro agregado correctamente", "success")
        return redirect(url_for("libros.users"))
        
    
    busqueda = request.args.get("buscar")
    if busqueda:
        libros = Libro.query.filter(
            (Libro.titulo.ilike(f"%{busqueda}%")) | (Libro.autor.ilike(f"%{busqueda}%"))
        ).all()

        if not libros:
            flash("No se encontró libro con este título o autor", "error")
            return redirect(url_for("libros.users"))
    else:
        libros = Libro.query.all()

    return render_template("index.html", productos = libros)
        
        
    
@libros_bp.route("/libros/eliminar/<int:id>", methods=["POST"])
def eliminar_libro(id):
    libro_a_eliminar = Libro.query.get(id)
    
    if libro_a_eliminar:
    
        db.session.delete(libro_a_eliminar)
        db.session.commit()
    
        flash("Libro eliminado correctamente", "success")
    
    else:
        flash("No se encontró el libro", "error")

    return redirect(url_for("libros.users"))

@libros_bp.route("/libros/editar/<int:id>", methods=["GET"])
def mostrar_formulario_edicion(id):
    libro = Libro.query.get_or_404(id)
    return render_template("editar.html", libro=libro)

@libros_bp.route("/libros/editar/<int:id>", methods=["POST"])
def actualizar_libro(id):
    libro = Libro.query.get_or_404(id)
    libro.titulo = request.form.get("titulo")
    libro.autor = request.form.get("autor")
    libro.editorial = request.form.get("editorial")

    db.session.commit()
    flash("Libro actualizado correctamente", "success")
    return redirect(url_for("libros.users"))

app/templates/editar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Editar Libro</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">

</head>
<body class="container mt-5">
    <h2>Editar Libro</h2>
    <form method="POST">
        <div class="mb-3">
            <label class="form-label">Título</label>
            <input type="text" name="titulo" value="{{ libro.titulo }}" class="form-control" required>
        </div>
        <div class="mb-3">
            <label class="form-label">Autor</label>
            <input type="text" name="autor" value="{{ libro.autor }}" class="form-control" required>
        </div>
        <div class="mb-3">
            <label class="form-label">Editorial</label>
            <input type="text" name="editorial" value="{{ libro.editorial }}" class="form-control" required>
        </div>
        <button type="submit" class="btn btn-primary">Guardar cambios</button>
        <a href="/libros" class="btn btn-secondary">Cancelar</a>
    </form>

</body>
</html>

app/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Libros</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
</head>
<body class="p-4">
    <div class="container">
        <h1 class="my-4 text-center">Lista de Libros</h1>

        


        <form action="/libros" method="POST" class="row g-3 mb-4">
            <div class="col-md-4">
                <input type="text" name="titulo" class="form-control" placeholder="Título" required>
            </div>
            <div class="col-md-4">
                <input type="text" name="autor" class="form-control" placeholder="Autor" required>
            </div>
            <div class="col-md-4">
                <input type="text" name="editorial" class="form-control" placeholder="Editorial" required>
            </div>
            <div class="col-12">
                <button type="submit" class="btn btn-primary">Agregar libro</button>
            </div>
        </form>

        <form method="GET" action="/libros" class="row g-3 mb-4">
                <div class="col-md-9">
                    <input type="text" name="buscar" class="form-control" placeholder="Buscar por título o autor">
                </div>

                <div class="col-md-3">
                    <button type="submit" class="btn btn-secondary w-100">Buscar</button>
                </div>
        </form>

        <table class="table table-striped table-bordered">
            <thead class="table-dark">
                <tr>
                    <th>ID</th>
                    <th>TITULO</th>
                    <th>AUTOR</th>
                    <th>EDITORIAL</th>
                    <th>ACCIONES</th>
                </tr>
            </thead>
            <tbody>
                {% for libro in productos %}
                    <tr>
                        <td>{{libro.id}}</td>
                        <td>{{libro.titulo}}</td>
                        <td>{{libro.autor}}</td>
                        <td>{{libro.editorial}}</td>
                        <td>
                            <form method="POST" action="{{url_for('libros.eliminar_libro', id=libro.id)}}" class="d-inline delete-form">
                                <button type="submit" class="btn btn-danger btn-sm">Eliminar</button>
                            </form>

                            <a href="/libros/editar/{{libro.id}}" class="btn btn-warning btn-sm">Editar</a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    
    {% with mensajes = get_flashed_messages(with_categories=true) %}
        {% if mensajes %}
            <script>
                Swal.fire({
                    title: '{{ mensajes[0][1] }}',
                    icon: '{{ mensajes[0][0] }}',
                    confirmButtonText: 'OK'
                });
            </script>
        {% endif %}
    {% endwith %}


    <script>
        document.addEventListener("DOMContentLoaded", function(){
            const deleteForms = document.querySelectorAll(".delete-form");

            deleteForms.forEach(form => {
                form.addEventListener("submit", function(e){
                    e.preventDefault();

                    Swal.fire({
                        title: '¿Estás seguro?',
                        text: "Esta acción no se puede deshacer",
                        icon: 'warning',
                        showCancelButton: true,
                        confirmButtonColor: '#d33',
                        cancelButtonColor: '#3085d6',
                        confirmButtonText: 'Sí, eliminar',
                        cancelButtonText: 'Cancelar'
                    }).then((result) => {
                        if (result.isConfirmed){
                            form.submit();
                        }
                    })
                })
            })
        })
    </script>
</body>
</html>

app/templates/users.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Lista de Usuarios</h1>
    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Nombre</th>
                <th>Email</th>
                <th>Activo</th>
                <th>Fecha de Registro</th>
            </tr>
        </thead>
        <tbody>
            {% for usuario in usuarios %}
                <tr>
                    <td>{{ usuario.id }}</td>
                    <td>{{ usuario.nombre }}</td>
                    <td>{{ usuario.email }}</td>
                    <td>{{ 'Sí' if usuario.activo else 'No' }}</td>
                    <td>{{ usuario.fecha_registro }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

    <form action="/users" method="POST"  enctype="multipart/form-data">
        <label for="">Nombre</label>
        <input type="text" name="nombre">

        <label for="">Email</label>
        <input type="email" name="correo">

        <button type="submit">Enviar</button>

    </form>
</body>
</html>